"""Initial1117

Revision ID: 0b2daacfa140
Revises: a70907a14325
Create Date: 2023-02-08 19:51:44.323017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2daacfa140'
down_revision = 'a70907a14325'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hotels_categories', ['id'])
    op.create_foreign_key(None, 'hotels_categories', 'hotels', ['id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels_categories', type_='foreignkey')
    op.drop_constraint(None, 'hotels_categories', type_='unique')
    # ### end Alembic commands ###
