"""Initial4

Revision ID: 2021654b5f47
Revises: 074b92f2e572
Create Date: 2023-02-07 08:49:43.854789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2021654b5f47'
down_revision = '074b92f2e572'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
