"""Initial

Revision ID: 221adb69c5c7
Revises: 2021654b5f47
Create Date: 2023-02-07 09:14:47.433359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221adb69c5c7'
down_revision = '2021654b5f47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
