"""Initial9

Revision ID: 27a4c6eaaec1
Revises: 43b974aff1bb
Create Date: 2023-02-08 16:26:02.505657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a4c6eaaec1'
down_revision = '43b974aff1bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
