"""New_bd5

Revision ID: 2a397ff1b9d5
Revises: ea1704625c6e
Create Date: 2023-02-08 17:39:01.077591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a397ff1b9d5'
down_revision = 'ea1704625c6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
