"""Initial123

Revision ID: 31082751ffb7
Revises: 4506c0bbca27
Create Date: 2023-02-08 18:50:57.400247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31082751ffb7'
down_revision = '4506c0bbca27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
