"""Final_db_8

Revision ID: 320bab0bd4c8
Revises: 7ffdc9de4ddf
Create Date: 2023-02-11 21:06:57.681337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320bab0bd4c8'
down_revision = '7ffdc9de4ddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
