"""Initial8

Revision ID: 43b974aff1bb
Revises: 156678f74795
Create Date: 2023-02-08 16:23:03.362877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b974aff1bb'
down_revision = '156678f74795'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
