"""Initial1113

Revision ID: 452dfbc2d0b0
Revises: d095218253d9
Create Date: 2023-02-08 19:42:18.810683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452dfbc2d0b0'
down_revision = 'd095218253d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hotels_categories', 'hotels', ['id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels_categories', type_='foreignkey')
    # ### end Alembic commands ###
