"""Initial126

Revision ID: 67e3c2083d16
Revises: 31bbedbf6ebb
Create Date: 2023-02-08 18:57:30.789847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e3c2083d16'
down_revision = '31bbedbf6ebb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hotels_categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels_categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('hotels', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
