"""Initial121

Revision ID: 70010c44903d
Revises: 747baa61206f
Create Date: 2023-02-08 18:22:18.960881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70010c44903d'
down_revision = '747baa61206f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels_categories',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels_categories')
    op.drop_table('hotels')
    # ### end Alembic commands ###
