"""Initial

Revision ID: 747baa61206f
Revises: 6c0c73718580
Create Date: 2023-02-08 18:20:18.716903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747baa61206f'
down_revision = '6c0c73718580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
