"""Final_db_6

Revision ID: 7ffdc9de4ddf
Revises: 117185476111
Create Date: 2023-02-11 21:04:46.982901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffdc9de4ddf'
down_revision = '117185476111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
