"""New_bd1

Revision ID: 96d20f1614ca
Revises: 7352052595e5
Create Date: 2023-02-08 16:33:05.591739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d20f1614ca'
down_revision = '7352052595e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
