"""Initial1118

Revision ID: 9b631a6811a4
Revises: 0b2daacfa140
Create Date: 2023-02-08 19:52:35.267269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b631a6811a4'
down_revision = '0b2daacfa140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hotels', ['category_id'])
    op.create_foreign_key(None, 'hotels_categories', 'hotels', ['id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels_categories', type_='foreignkey')
    op.drop_constraint(None, 'hotels', type_='unique')
    # ### end Alembic commands ###
