"""Initial1114

Revision ID: adfd11376922
Revises: 452dfbc2d0b0
Create Date: 2023-02-08 19:47:02.126838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfd11376922'
down_revision = '452dfbc2d0b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'hotels', ['category_id'])
    op.create_foreign_key(None, 'hotels_categories', 'hotels', ['id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels_categories', type_='foreignkey')
    op.drop_constraint(None, 'hotels', type_='unique')
    op.alter_column('hotels', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
