"""New_bd2

Revision ID: e73766a5cf32
Revises: 96d20f1614ca
Create Date: 2023-02-08 16:35:03.523722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73766a5cf32'
down_revision = '96d20f1614ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
