"""new database6

Revision ID: ebf0c3c4b420
Revises: 2a6f44656431
Create Date: 2023-02-21 15:51:40.783295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf0c3c4b420'
down_revision = '2a6f44656431'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'total_cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'total_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'total_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'total_cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
