"""new database7

Revision ID: fd593ddab068
Revises: ebf0c3c4b420
Create Date: 2023-02-21 15:52:25.427117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd593ddab068'
down_revision = 'ebf0c3c4b420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'total_cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'total_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'total_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'total_cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
